version: '3'


services:

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "7100:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "7100:3000"
    volumes:
      - ./data/prometheus/etc:/etc/prometheus
      - ./data/prometheus/data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

